title: Best practices for frontend development
description: Best practices to be used in frontend development
theme: just-the-docs

url: https://anukrishnan-ks.github.io/Best-practices-for-frontend-development

aux_links:
  Template Repository: https://github.com/anukrishnan-ks/Best-practices-for-frontend-development
